// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkXFXH6xglyfHL62OHdgwIpREZOPkT8JQ',
    appId: '1:666105308068:web:b26e24a5c860481245d731',
    messagingSenderId: '666105308068',
    projectId: 'fieldproject-b7dc5',
    authDomain: 'fieldproject-b7dc5.firebaseapp.com',
    storageBucket: 'fieldproject-b7dc5.firebasestorage.app',
    measurementId: 'G-P02YVSF9ZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHHwEzRTdSoxrKNi5tgpRz5iXEYg0_LfI',
    appId: '1:666105308068:android:4a4e3e701cc1528d45d731',
    messagingSenderId: '666105308068',
    projectId: 'fieldproject-b7dc5',
    storageBucket: 'fieldproject-b7dc5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu78Ysps1xe44jtmJ5rvoQVcJoC7v5s8M',
    appId: '1:666105308068:ios:2190954bcac1a9c045d731',
    messagingSenderId: '666105308068',
    projectId: 'fieldproject-b7dc5',
    storageBucket: 'fieldproject-b7dc5.firebasestorage.app',
    iosBundleId: 'com.smartbuilding.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu78Ysps1xe44jtmJ5rvoQVcJoC7v5s8M',
    appId: '1:666105308068:ios:2190954bcac1a9c045d731',
    messagingSenderId: '666105308068',
    projectId: 'fieldproject-b7dc5',
    storageBucket: 'fieldproject-b7dc5.firebasestorage.app',
    iosBundleId: 'com.smartbuilding.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkXFXH6xglyfHL62OHdgwIpREZOPkT8JQ',
    appId: '1:666105308068:web:5d6c7726409f791745d731',
    messagingSenderId: '666105308068',
    projectId: 'fieldproject-b7dc5',
    authDomain: 'fieldproject-b7dc5.firebaseapp.com',
    storageBucket: 'fieldproject-b7dc5.firebasestorage.app',
    measurementId: 'G-D5V75DR04B',
  );
}
